version: '3.8'

services:
  # The FastAPI Backend
  api:
    build: .
    container_name: serene-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./app:/app/app # Mount app dir for easier debugging/hot reload if needed (remove in prod if preferred)

  # The LiveKit Agent Worker
  agent:
    build: .
    container_name: serene-agent
    command: python start_agent.py start
    env_file:
      - .env
    restart: always
    depends_on:
      - api
    # No ports needed for the agent as it connects OUT to LiveKit Cloud

    # The React Frontend
  frontend:
    build:
      context: ../frontend
      args:
        - VITE_API_URL=http://3.236.8.180:8000
        - VITE_LIVEKIT_URL=wss://rag-q8jnl16x.livekit.cloud
        - VITE_AUTH0_DOMAIN=dev-bqdnlxk68cmc4623.us.auth0.com
        - VITE_AUTH0_CLIENT_ID=PKpb3rwcO5Qds3ZmFXtzycXX9vja9D6I
    container_name: serene-frontend
    ports:
      - "80:80"
    restart: always
